# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_mainView.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_mainView(object):
    def setupUi(self, mainView):
        mainView.setObjectName(_fromUtf8("mainView"))
        mainView.resize(1104, 909)
        self.mainFrame = QtWidgets.QWidget(mainView)
        self.mainFrame.setObjectName(_fromUtf8("mainFrame"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.titleLabel = QtWidgets.QLabel(self.mainFrame)
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.verticalLayout.addWidget(self.titleLabel)
        self.mainWidgetFrame = QtWidgets.QFrame(self.mainFrame)
        self.mainWidgetFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainWidgetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainWidgetFrame.setObjectName(_fromUtf8("mainWidgetFrame"))
        self.formLayout_2 = QtWidgets.QFormLayout(self.mainWidgetFrame)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtWidgets.QFrame(self.mainWidgetFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(150, 40))
        self.frame.setMaximumSize(QtCore.QSize(150, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lpSection = QtWidgets.QSpinBox(self.frame)
        self.lpSection.setMinimumSize(QtCore.QSize(40, 0))
        self.lpSection.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lpSection.setFont(font)
        self.lpSection.setObjectName(_fromUtf8("lpSection"))
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lpSection)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.mainWidgetFrame)
        self.frame_2.setMinimumSize(QtCore.QSize(149, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(150, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lpSentence = QtWidgets.QSpinBox(self.frame_2)
        self.lpSentence.setMinimumSize(QtCore.QSize(40, 0))
        self.lpSentence.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lpSentence.setFont(font)
        self.lpSentence.setObjectName(_fromUtf8("lpSentence"))
        self.horizontalLayout_3.addWidget(self.lpSentence)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_2, QtCore.Qt.AlignLeft)
        self.getSentence = QtWidgets.QPushButton(self.mainWidgetFrame)
        self.getSentence.setMinimumSize(QtCore.QSize(150, 0))
        self.getSentence.setMaximumSize(QtCore.QSize(150, 16777215))
        self.getSentence.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.getSentence.setFont(font)
        self.getSentence.setObjectName(_fromUtf8("getSentence"))
        self.verticalLayout_2.addWidget(self.getSentence)
        self.line = QtWidgets.QFrame(self.mainWidgetFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.partWord = QtWidgets.QTextEdit(self.mainWidgetFrame)
        self.partWord.setMinimumSize(QtCore.QSize(120, 31))
        self.partWord.setMaximumSize(QtCore.QSize(120, 23))
        self.partWord.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.partWord.setFont(font)
        self.partWord.setObjectName(_fromUtf8("partWord"))
        self.verticalLayout_2.addWidget(self.partWord)
        self.frame_3 = QtWidgets.QFrame(self.mainWidgetFrame)
        self.frame_3.setMinimumSize(QtCore.QSize(120, 40))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.runeCount = QtWidgets.QSpinBox(self.frame_3)
        self.runeCount.setMinimumSize(QtCore.QSize(40, 0))
        self.runeCount.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.runeCount.setFont(font)
        self.runeCount.setMinimum(1)
        self.runeCount.setMaximum(14)
        self.runeCount.setProperty("value", 1)
        self.runeCount.setObjectName(_fromUtf8("runeCount"))
        self.horizontalLayout.addWidget(self.runeCount)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.dictWords = QtWidgets.QRadioButton(self.mainWidgetFrame)
        self.dictWords.setMinimumSize(QtCore.QSize(120, 0))
        self.dictWords.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dictWords.setFont(font)
        self.dictWords.setObjectName(_fromUtf8("dictWords"))
        self.verticalLayout_2.addWidget(self.dictWords)
        self.masterWords = QtWidgets.QRadioButton(self.mainWidgetFrame)
        self.masterWords.setMinimumSize(QtCore.QSize(150, 0))
        self.masterWords.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.masterWords.setFont(font)
        self.masterWords.setObjectName(_fromUtf8("masterWords"))
        self.verticalLayout_2.addWidget(self.masterWords)
        self.showWordsList = QtWidgets.QPushButton(self.mainWidgetFrame)
        self.showWordsList.setMinimumSize(QtCore.QSize(150, 0))
        self.showWordsList.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showWordsList.setFont(font)
        self.showWordsList.setObjectName(_fromUtf8("showWordsList"))
        self.verticalLayout_2.addWidget(self.showWordsList)
        self.line_2 = QtWidgets.QFrame(self.mainWidgetFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        self.findNGrams = QtWidgets.QPushButton(self.mainWidgetFrame)
        self.findNGrams.setMinimumSize(QtCore.QSize(150, 0))
        self.findNGrams.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.findNGrams.setFont(font)
        self.findNGrams.setObjectName(_fromUtf8("findNGrams"))
        self.verticalLayout_2.addWidget(self.findNGrams)
        self.lpImage1 = QtWidgets.QLabel(self.mainWidgetFrame)
        self.lpImage1.setMinimumSize(QtCore.QSize(150, 225))
        self.lpImage1.setMaximumSize(QtCore.QSize(150, 225))
        self.lpImage1.setObjectName(_fromUtf8("lpImage1"))
        self.verticalLayout_2.addWidget(self.lpImage1)
        self.lpImage2 = QtWidgets.QLabel(self.mainWidgetFrame)
        self.lpImage2.setMinimumSize(QtCore.QSize(150, 225))
        self.lpImage2.setMaximumSize(QtCore.QSize(150, 225))
        self.lpImage2.setObjectName(_fromUtf8("lpImage2"))
        self.verticalLayout_2.addWidget(self.lpImage2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.wordWidgetGrid = QtWidgets.QGridLayout()
        self.wordWidgetGrid.setObjectName(_fromUtf8("wordWidgetGrid"))
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.wordWidgetGrid)
        self.verticalLayout.addWidget(self.mainWidgetFrame)
        mainView.setCentralWidget(self.mainFrame)
        self.menubar = QtWidgets.QMenuBar(mainView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        mainView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainView)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainView.setStatusBar(self.statusbar)

        self.retranslateUi(mainView)
        QtCore.QMetaObject.connectSlotsByName(mainView)

    def retranslateUi(self, mainView):
        mainView.setWindowTitle(_translate("mainView", "MainWindow", None))
        self.titleLabel.setText(_translate("mainView", "Patience is a virtue", None))
        self.label.setText(_translate("mainView", "Section", None))
        self.label_2.setText(_translate("mainView", "Sentence", None))
        self.getSentence.setText(_translate("mainView", "Get Sentence", None))
        self.partWord.setHtml(_translate("mainView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">A</span></p></body></html>", None))
        self.label_3.setText(_translate("mainView", "Rune Count", None))
        self.dictWords.setText(_translate("mainView", "Dict. Words", None))
        self.masterWords.setText(_translate("mainView", "Master Words", None))
        self.showWordsList.setText(_translate("mainView", "Show Word List", None))
        self.findNGrams.setText(_translate("mainView", "Find Ngrams", None))
        self.lpImage1.setText(_translate("mainView", "Page Image 1 ", None))
        self.lpImage2.setText(_translate("mainView", "Page Image 2", None))

